export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const MINUS_QUANTITY = 'MINUS_QUANTITY';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';


